[package]
name = "embedded-spi"
description = "Rust embedded driver helper package"
repository = "https://github.com/ryankurte/rust-spi-hal"
version = "0.6.2"
authors = ["Ryan Kurte <ryankurte@gmail.com>"]
edition = "2018"
license = "MIT"

[features]
mock = []
ffi = [ "libc" ]
utils = [ "hal" ]
hal = [ "toml", "structopt", "serde", "simplelog" ]
hal-cp2130 = [ "driver-cp2130" ]
hal-linux = [ "linux-embedded-hal" ]
default = [ "mock", "hal", "hal-cp2130", "hal-linux" ]

[dependencies]
embedded-hal = { version = "1.0.0-alpha.0" }
linux-embedded-hal = { version = "0.3.0", optional = true }
libc = { version = "0.2.54", optional = true }
log = "0.4.6"
serde = { version = "1.0.91", features = ["derive"], optional = true }
toml = { version = "0.5.1", optional = true }
structopt = { version = "0.3.11", optional = true }
simplelog = { version = "0.5.3", optional = true }
driver-cp2130 = { version = "1.0.0-alpha.0", optional = true, features = ["transactional"] }


[patch.crates-io]
embedded-hal = { git = "https://github.com/ryankurte/embedded-hal", branch = "feature/spi-transactions" }
linux-embedded-hal = { git = "https://github.com/ryankurte/linux-embedded-hal.git", branch = "feature/spi-transactions" }

