[package]
name = "embedded-spi"
description = "Rust embedded driver helper package"
repository = "https://github.com/ryankurte/rust-embedded-spi"
version = "0.6.1"
authors = ["Ryan Kurte <ryankurte@gmail.com>"]
edition = "2018"
license = "MIT"

[features]
mock = []
ffi = [ "libc" ]
utils = [ "toml", "structopt", "serde", "simplelog", "linux-embedded-hal" ]
hal = [ "toml", "structopt", "serde", "simplelog" ]
hal-cp2130 = [ "driver-cp2130" ]
hal-linux = [ "linux-embedded-hal" ]
default = [ "mock", "hal", "hal-cp2130" ]

[dependencies]
embedded-hal = { version = "0.2.3", features = ["unproven"] }
linux-embedded-hal = { version = "0.3.0", optional = true }
libc = { version = "0.2.54", optional = true }
log = "0.4.6"
serde = { version = "1.0.91", features = ["derive"], optional = true }
toml = { version = "0.5.1", optional = true }
structopt = { version = "0.2.15", optional = true }
simplelog = { version = "0.5.3", optional = true }
#driver-cp2130 = { version = "0.3.1", optional = true }
driver-cp2130 = { path = "../rust-driver-cp2130", optional=true }

[patch.crates-io]
embedded-hal = { git = "https://github.com/ryankurte/embedded-hal", branch = "feature/spi-i2c-transactions" }
#linux-embedded-hal = { git = "https://github.com/ryankurte/linux-embedded-hal.git", branch = "feature/transactional" }

