[package]
name = "driver-pal"
description = "Rust embedded driver helper package"
repository = "https://github.com/ryankurte/rust-spi-hal"
version = "1.0.0-alpha.0"
authors = ["Ryan Kurte <ryankurte@gmail.com>"]
edition = "2018"
license = "MIT"

[features]
mock = []
ffi = [ "libc" ]
utils = [ "hal" ]
hal = [ "toml", "structopt", "serde", "simplelog" ]
hal-cp2130 = [ "driver-cp2130" ]
hal-linux = [ "linux-embedded-hal" ]
default = [ "mock", "hal", "hal-cp2130", "hal-linux" ]

[dependencies]
log = "0.4.6"
embedded-hal = { version = "1.0.0-alpha.2" }

linux-embedded-hal = { version = "0.3.0", optional = true }
driver-cp2130 = { version = "1.0.0-alpha.1", optional = true }
libc = { version = "0.2.54", optional = true }

serde = { version = "1.0.91", features = ["derive"], optional = true }
toml = { version = "0.5.1", optional = true }

structopt = { version = "0.3.11", optional = true }
simplelog = { version = "0.5.3", optional = true }


[patch.crates-io]
# embedded-hal patch to master for SPI transactions, remove at v1.0.0-alpha.3
embedded-hal = { git = "https://github.com/rust-embedded/embedded-hal", branch = "master" }

# linux-embedded-hal patch to add spi transaction support, remove at v1.0.0-alpha.0
linux-embedded-hal = { git = "https://github.com/ryankurte/linux-embedded-hal.git", branch = "feature/spi-transactions" }

# CP2130 patch for transactional support, release blocked on both above
driver-cp2130 = { git = "https://github.com/ryankurte/rust-driver-cp2130.git", branch = "master" }
